---
title: "Data Exploration Nursery"
author: "NicholasDi and Erin Franke"
date: '2022-04-18'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidycensus)
library(tidyverse)
library(survey)
library(srvyr)
library(sf)
library(ggtext)
library(broom)
library(spdep)
library(janitor)

load("DataShapefiles/lead_spatial.RData")
river_lakes <- st_read("DataShapefiles/shp_water_lakes_rivers")
roads <- st_read("DataShapefiles/tl_2019_27_prisecroads")
roads_sub <- st_crop(roads,st_bbox(lead_census))
```


```{r}
lead_census_clean <- lead_census %>%
  filter(!is.na(medincomeE), !is.na(propHomesBuiltPre1950), !is.na(PopE))
```

```{r}
lead_census_clean %>% 
  select(tested,numChildtestingage) %>% 
  st_drop_geometry()
lead_census_clean <- lead_census_clean %>% 
  mutate(AREA = st_area(lead_census_clean))

lead_census_clean <- lead_census_clean %>% 
  mutate(AREA1 = as.vector(AREA))

lead_census_clean %>%  st_drop_geometry() %>% ggplot(aes(y=tested/numChildtestingage, x = percent)) +
  geom_point() 
```

```{r}
lead_census_clean %>% ggplot(aes(x=medageE, fill = factor(HighLead))) +
  geom_density(alpha = 0.5) 

lead_census_clean %>% ggplot(aes(x = CensusAgeE, fill = factor(HighLead)))+
  geom_density(alpha = 0.35)+
  facet_wrap(~TestingHigh)

lead_census_clean <- lead_census_clean %>% 
  mutate(WhyUNoTest = case_when(TestingHigh == 0 & CensusAgeE < 66 & HighLead == 1 ~ 1,
                                TRUE ~ 0))
```
Interesting that there is a population of people living in newer houses that aren't getting tested. 

```{r}
lead_census_clean %>%
  ggplot()+
  geom_sf(aes(fill = WhyUNoTest), lwd = 0.2, color = "white")+
  theme_classic()+
  labs(title = "Places with Highlead, new houses but not getting tested", fill = "")+
  theme(axis.line = element_blank(), 
        axis.text = element_blank(), 
        axis.ticks = element_blank(),
        plot.title.position = "plot", 
        plot.title = element_markdown(family = "mono", size = 9))+
  scale_fill_viridis_c()
```

Looking at testing variable and relationships:
- High income census tracts tend to not have high lead \
```{r}
lead_testing <- lead_census_clean %>%
  st_drop_geometry() %>%
  mutate(testRatio = tested/numChildtestingage, 
         CensusAgeE = propHomesBuiltPre1950 * runif(1, 72,122) + propHomesBuilt1950to1969*62.5 + propHomesBuilt1970to1989*42.5 + propHomesBuilt1990to2009*22.5 + propHomesBuilt2010tonow*6, highIncome = case_when(medincomeE > 100000 ~ "highInc",
                                TRUE ~ "lowerInc"),
         Homecat = cut(CensusAgeE, 3), 
         multipleTest = case_when(testRatio > 1 ~ "manyTest",
                                  TRUE ~ "lessTest"))
  
lead_testing %>%
  ggplot(aes(x=medincomeE, y=testRatio, color=as.factor(HighLead)))+
  geom_point()

lead_testing %>%
  ggplot(aes(x=CensusAgeE, y=testRatio, color=as.factor(HighLead)))+
  geom_point()

# new homes get tested less often, especially with low lead levels
# older homes get tested more, especially when with higher lead levels
lead_testing %>%
  tabyl(Homecat, multipleTest, HighLead)

# if you have high lead, income isn't necessarily a factor for how much you are tested
lead_testing %>%
  filter(HighLead == 1) %>%
  ggplot(aes(x=medincomeE, fill = multipleTest))+
  geom_density(alpha=0.5)+
  theme_classic()+
  scale_fill_manual(values = c("red", "navy"))

lead_testing %>%
  group_by(HighLead, multipleTest) %>%
  summarize(mean(NumHouseE),mean(CensusAgeE), mean(medincomeE), mean(PopE), mean(medageE))
```


